logging:
  file:
    name: app.log

server:
  address: 0.0.0.0
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}  # Default to 8080 unless SERVER_PORT is specified

spring:
  datasource:
    username: ${DATASOURCE_USERNAME:sa}  # Defaults to 'sa' if DATASOURCE_USERNAME not specified
    password: ${DATASOURCE_PASSWORD:''}  # Empty password by default
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}  # Defaults to H2 in-memory DB if DATASOURCE_URL not specified
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect  # Setting Hibernate dialect for PostgreSQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true  # Logs all SQL statements

springdoc:
  api-docs:
    path: '/api/v3/api-docs'
  swagger-ui:
    path: '/api/swagger-ui.html'
    configUrl: '/api/v3/api-docs/swagger-config'
    disable-swagger-default-url: true
    url: '/api/v3/api-docs'
